//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RailData.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Incident
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Incident()
        {
            this.GISPointOfInterest = new HashSet<GISPointOfInterest>();
        }
    
        public int Id { get; set; }
        [Display(Name = "Date", AutoGenerateFilter = true)]
        public System.DateTime IncidentDate { get; set; }
        public int IncidentType { get; set; }
        public int ReporterId { get; set; }
        public string Description { get; set; }
    
        public virtual TypeOfIncident TypeOfIncident { get; set; }
        public virtual IncidentImage IncidentImage { get; set; }
        public virtual TypeOfReporter TypeOfReporter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GISPointOfInterest> GISPointOfInterest { get; set; }
    }
}
