//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RailData.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RailDataEntities : DbContext
    {
        public RailDataEntities()
            : base("name=RailDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GISPointOfInterest> GISPointOfInterest { get; set; }
        public virtual DbSet<Incident> Incident { get; set; }
        public virtual DbSet<IncidentImage> IncidentImage { get; set; }
        public virtual DbSet<spatial_ref_sys> spatial_ref_sys { get; set; }
        public virtual DbSet<TypeOfIncident> TypeOfIncident { get; set; }
        public virtual DbSet<TypeOfReporter> TypeOfReporter { get; set; }
        public virtual DbSet<layer> layer { get; set; }
        public virtual DbSet<topology> topology { get; set; }
    }
}
